name: xcode_gen_example
configs:
  Debug: debug
  Beta: release
  AppStore: release
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 11.1
targets:
  xcode_gen_example:
    dependencies:
      - target: hiratsuka-test
      - target: logging_framework
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: RxBlocking
      - carthage: SVProgressHUD
#      - framework: logging_framework/Output/logging_framework.framework
    type: application
    platform: iOS
    sources: xcode_gen_example
    settings:
      configs:
        Debug:
          DEVELOPMENT_TEAM: P8D4MRXE78
          CODE_SIGN_IDENTITY: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: match Development hiratsuka-test.deug
          BUNDLE_ID: hiratsuka-test.debug
          PRODUCT_NAME: debug-hiratsuka
          OTHER_SWIFT_FLAGS: -D DEBUG -Xfrontend -debug-time-function-bodies
        Beta:
          DEVELOPMENT_TEAM: S56GZ64EWS
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AdHoc hiratsuka-test.beta
          BUNDLE_ID: hiratsuka-test.beta
          PRODUCT_NAME: beta-hiratsuka
          OTHER_SWIFT_FLAGS: -Xfrontend -debug-time-function-bodies
        AppStore:
          DEVELOPMENT_TEAM: S56GZ64EWS
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AppStore hiratsuka-test.prod
          BUNDLE_ID: hiratsuka-test.prod
          PRODUCT_NAME: prod-hiratsuka
          OTHER_SWIFT_FLAGS: -Xfrontend -debug-time-function-bodies
      base:
        ENABLE_BITCODE: NO
        CODE_SIGN_STYLE: Manual
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: ${inherited}
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: xcode_gen_example/info.plist
        PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID}
        SWIFT_VERSION: 4.2
        IPHONEOS_DEPLOYMENT_TARGET: 11.1
    postbuildScripts:
      - script: ${PROJECT_DIR}/test.sh
        name: hiratsuka test  
    scheme:
      testTargets: xcode_gen_exampleTests
  xcode_gen_exampleTests:
    type: bundle.unit-test
    platform: iOS
    sources: xcode_gen_exampleTests
    settings:
      INFOPLIST_FILE: xcode_gen_exampleTests/Supporting Files/info.plist
      CODE_SIGN_STYLE: Automatic
      SWIFT_VERSION: 4.2
      TEST_HOST: ${BUILT_PRODUCTS_DIR}/xcode_gen_example.app
      DEVELOPMENT_TEAM: S56GZ64EWS
  hiratsuka-test:
    type: framework
    platform: iOS
    sources: hiratsuka-test
    settings:
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: ${inherited}
      CODE_SIGN_STYLE: Automatic
      INFOPLIST_FILE: hiratsuka-test/info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.nonchalant.hiratsuka-test
      SWIFT_VERSION: 4.2
      DEVELOPMENT_TEAM: S56GZ64EWS
      IPHONEOS_DEPLOYMENT_TARGET: 11.1
    scheme:
      testTargets: hiratsuka-testTests
  hiratsuka-testTests:
    type: bundle.unit-test
    platform: iOS
    sources: hiratsuka-testTests
    settings:
      INFOPLIST_FILE: hiratsuka-testTests/info.plist
      CODE_SIGN_STYLE: Automatic
      SWIFT_VERSION: 4.2
      TEST_HOST: ${BUILT_PRODUCTS_DIR}/hiratsuka-test.framework
      DEVELOPMENT_TEAM: S56GZ64EWS
      IPHONEOS_DEPLOYMENT_TARGET: 11.1
  logging_framework:
    type: framework
    platform: iOS
    sources: logging_framework/logging_framework
    settings:
      CODE_SIGN_STYLE: Automatic
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: ${inherited}
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      INFOPLIST_FILE: logging_framework/logging_framework/info.plist
      PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID}
      SWIFT_VERSION: 4.2
      DEVELOPMENT_TEAM: S56GZ64EWS
      IPHONEOS_DEPLOYMENT_TARGET: 11.1
    scheme:
      testTargets: logging_frameworkTests
  logging_frameworkTests:
    type: bundle.unit-test
    platform: iOS
    sources: logging_framework/logging_frameworkTests
    settings:
      INFOPLIST_FILE: logging_framework/logging_frameworkTests/info.plist
      CODE_SIGN_STYLE: Automatic
      SWIFT_VERSION: 4.2
      TEST_HOST: ${BUILT_PRODUCTS_DIR}/logging_framework/logging_framework.framework
      DEVELOPMENT_TEAM: S56GZ64EWS
      IPHONEOS_DEPLOYMENT_TARGET: 11.1

