name: xcode_gen_example
configs:
  Debug: debug
  Beta: release
  AppStore: release
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 11.1
targets:
  xcode_gen_example:
    dependencies:
      - target: hiratsuka-test
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: RxBlocking
      - carthage: SVProgressHUD
      - framework: logging_framework/Output/logging_framework.framework
    type: application
    platform: iOS
    sources: xcode_gen_example
    settings:
      configs:
        Debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          BUNDLE_ID: hiratsuka-test.debug
        Beta:
          CODE_SIGN_IDENTITY: iPhone Distribution
          BUNDLE_ID: hiratsuka-test.beta
        AppStore:
          CODE_SIGN_IDENTITY: iPhone Distribution
          BUNDLE_ID: hiratsuka-test.prod
      base:    
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: ${inherited}
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: xcode_gen_example/info.plist
        PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID}
        SWIFT_VERSION: 4.2
        DEVELOPMENT_TEAM: S56GZ64EWS
        IPHONEOS_DEPLOYMENT_TARGET: 11.1
    postbuildScripts:
      - script: $(PROJECT_DIR)/test.sh
        name: hiratsuka test  
    scheme:
      testTargets: xcode_gen_exampleTests
  xcode_gen_exampleTests:
    type: bundle.unit-test
    platform: iOS
    sources: xcode_gen_exampleTests
    settings:
      INFOPLIST_FILE: xcode_gen_exampleTests/Supporting Files/info.plist
      CODE_SIGN_STYLE: Automatic
      SWIFT_VERSION: 4.2
      TEST_HOST: ${BUILT_PRODUCTS_DIR}/xcode_gen_example.app
      DEVELOPMENT_TEAM: S56GZ64EWS
  hiratsuka-test:
    type: framework
    platform: iOS
    sources: hiratsuka-test
    settings:
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: ${inherited}
      CODE_SIGN_STYLE: Automatic
      INFOPLIST_FILE: hiratsuka-test/info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.nonchalant.hiratsuka-test
      SWIFT_VERSION: 4.2
      DEVELOPMENT_TEAM: S56GZ64EWS
      IPHONEOS_DEPLOYMENT_TARGET: 11.1
    scheme:
      testTargets: hiratsuka-testTests
  hiratsuka-testTests:
    type: bundle.unit-test
    platform: iOS
    sources: hiratsuka-testTests
    settings:
      INFOPLIST_FILE: hiratsuka-testTests/info.plist
      CODE_SIGN_STYLE: Automatic
      SWIFT_VERSION: 4.2
      TEST_HOST: ${BUILT_PRODUCTS_DIR}/hiratsuka-test.framework
      DEVELOPMENT_TEAM: S56GZ64EWS
